BEGIN;
  -- Already set by citus base image
  -- CREATE EXTENSION IF NOT EXISTS citus CASCADE;

  CREATE EXTENSION IF NOT EXISTS pg_cron CASCADE;
  CREATE EXTENSION IF NOT EXISTS btree_gist CASCADE;
  CREATE EXTENSION IF NOT EXISTS "postgres-json-schema" CASCADE;
  CREATE EXTENSION IF NOT EXISTS periods CASCADE;
  CREATE EXTENSION IF NOT EXISTS pg_stat_statements CASCADE;
  CREATE EXTENSION IF NOT EXISTS pgcrypto CASCADE;
  CREATE EXTENSION IF NOT EXISTS "uuid-ossp" CASCADE;
  CREATE EXTENSION IF NOT EXISTS fuzzystrmatch CASCADE;
  CREATE EXTENSION IF NOT EXISTS hll CASCADE;
  CREATE EXTENSION IF NOT EXISTS pg_prewarm CASCADE;
  CREATE EXTENSION IF NOT EXISTS hypopg CASCADE;
  CREATE EXTENSION IF NOT EXISTS hstore CASCADE;
  CREATE EXTENSION IF NOT EXISTS pg_trgm CASCADE;
  CREATE EXTENSION IF NOT EXISTS pg_repack CASCADE;
  CREATE EXTENSION IF NOT EXISTS moddatetime CASCADE;
  CREATE EXTENSION IF NOT EXISTS topn CASCADE;
  CREATE EXTENSION IF NOT EXISTS cstore_fdw CASCADE;
  CREATE EXTENSION IF NOT EXISTS pgautofailover CASCADE;

  -- Already set by citus base image
  -- UPDATE pg_dist_node_metadata SET metadata=jsonb_insert(metadata, '{docker}', 'true');
COMMIT;
